/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Samuel
 */
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane; 

public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
        this.setLocationRelativeTo(null);
       InicioZero("0","0","0","0","0");
       BotonPago.setEnabled(false);
      
            
    }
    public void InicioZero(String a, String b, String c, String d, String e){
    
    Perfume.setText(a);
    Cartera.setText(b);
    Pantalon.setText(c);
    Zapato.setText(d);
    Camisa.setText(e);
    }
    
    public void NombreCliente(String Name){
    
    jLabel10.setText(Name);
    
    }
 
    public void tomardatoPerfume(String dato)
    {
        
            Perfume.setText(dato);
            
    }
    
    public void tomardatoCartera(String dato)
    {
            Cartera.setText(dato);
           
    }
    
    public void tomardatoPantalon(String dato)
    {
            Pantalon.setText(dato);
    }
    
    public void tomardatoZapato(String dato)
    {
            Zapato.setText(dato);
    }
    
    public void tomardatoCamisa(String dato)
    {
            Camisa.setText(dato);
    }
    
    public void obtenerNombreCliente(String nombre){
        lblNombreUsuario.setText(nombre);
    }
    
    public void Calculo(){
     BotonPago.setEnabled(true);
    double Perf,Car,Pan,Zap,Cam,subtotal,impuesto,totalfinal;
   // DecimalFormat df = new DecimalFormat("#.##");
    
    Perf =Integer.parseInt(Perfume.getText());
    Car = Integer.parseInt(Cartera.getText());
    Pan = Integer.parseInt(Pantalon.getText());
    Zap = Integer.parseInt(Zapato.getText());
    Cam = Integer.parseInt(Camisa.getText());
    
    subtotal = Perf+Car+Pan+Zap+Cam;
    String sb = subtotal + "";
     tsub.setText(sb);
    impuesto = subtotal*0.18;
    String isv = String.format("%.2f",impuesto);
     ISV.setText(isv);
    totalfinal= subtotal + impuesto;
    String TFinal = totalfinal + "";
    TxtF.setText(TFinal);
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Cartera = new javax.swing.JTextField();
        Perfume = new javax.swing.JTextField();
        Pantalon = new javax.swing.JTextField();
        Zapato = new javax.swing.JTextField();
        Camisa = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BotonPago = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tsub = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ISV = new javax.swing.JTextField();
        TxtF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FACTURA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel10)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(6, 6, 455, 64);

        Cartera.setEditable(false);
        Cartera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarteraActionPerformed(evt);
            }
        });
        jPanel1.add(Cartera);
        Cartera.setBounds(400, 180, 50, 26);

        Perfume.setEditable(false);
        Perfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfumeActionPerformed(evt);
            }
        });
        jPanel1.add(Perfume);
        Perfume.setBounds(400, 140, 50, 26);

        Pantalon.setEditable(false);
        jPanel1.add(Pantalon);
        Pantalon.setBounds(400, 220, 50, 26);

        Zapato.setEditable(false);
        jPanel1.add(Zapato);
        Zapato.setBounds(400, 260, 50, 26);

        Camisa.setEditable(false);
        Camisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamisaActionPerformed(evt);
            }
        });
        jPanel1.add(Camisa);
        Camisa.setBounds(400, 300, 50, 26);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Perfumes");

        jLabel6.setText("Carteras");

        jLabel7.setText("Pantalones");

        jLabel8.setText("Zapatos");

        jLabel9.setText("Camisas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 130, 130, 200);

        jButton1.setText("Seguir Comprando");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Abortar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BotonPago.setText("Pagar");
        BotonPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonPagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonPagoMouseExited(evt);
            }
        });
        BotonPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPagoActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salir)
                .addGap(18, 18, 18)
                .addComponent(BotonPago)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(BotonPago)
                    .addComponent(Salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 420, 440, 60);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Subtotal");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(20, 10, 70, 20);

        tsub.setEditable(false);
        jPanel5.add(tsub);
        tsub.setBounds(10, 30, 71, 26);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ISV 18%");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(170, 10, 70, 20);

        ISV.setEditable(false);
        jPanel5.add(ISV);
        ISV.setBounds(170, 30, 71, 26);

        TxtF.setEditable(false);
        jPanel5.add(TxtF);
        TxtF.setBounds(320, 30, 71, 26);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total Pagar");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(320, 10, 70, 20);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 350, 440, 60);

        lblNombreUsuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblNombreUsuario);
        lblNombreUsuario.setBounds(100, 60, 290, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Cliente:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 60, 70, 40);

        jLabel21.setText("Total");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(400, 110, 36, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPagoActionPerformed
         Object[] opciones = { "Si", "No"}; 
  
        int decision = JOptionPane.showOptionDialog( 
            null,  
            "¿Desea confirmar su compra?",
            "Opciones", 
            JOptionPane.YES_NO_CANCEL_OPTION, 
            JOptionPane.QUESTION_MESSAGE, // Message type (question icon) 
            null, // Custom icon (null means no custom icon) 
            opciones, 
            opciones[0] 
                
        ); 
                    
        // Check the user's choice and display a 
        // corresponding message 
        if (decision == JOptionPane.YES_OPTION) { 
            // If the user chose 'Yes' 
            // show a message indicating that they are 
            // proceeding 
            JOptionPane.showMessageDialog(null,"Transaccion Confirmada"); 
            
            
            
        } 
        else if (decision == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Transaccion No Confirmada", "Transaccion No Confirmada", JOptionPane.ERROR_MESSAGE);
            
        } 
        

        
    }//GEN-LAST:event_BotonPagoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Operacion Abortada", "Operacion Abortada", JOptionPane.ERROR_MESSAGE);
    Perfume.setText("-");
    Cartera.setText("-");
    Pantalon.setText("-");
    Zapato.setText("-");
    Camisa.setText("-");
    tsub.setText("-");
    ISV.setText("-");
    TxtF.setText("-");
    BotonPago.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfumeActionPerformed

    private void CarteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarteraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarteraActionPerformed

    private void CamisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamisaActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground( new Color(255,102,102));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jButton2.setBackground( new Color(255,102,102));
    }//GEN-LAST:event_jButton2MouseEntered

    private void BotonPagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPagoMouseEntered
        // TODO add your handling code here:
        BotonPago.setBackground( new Color(255,102,102));
    }//GEN-LAST:event_BotonPagoMouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(  Color.WHITE);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setBackground(  Color.WHITE);
    }//GEN-LAST:event_jButton2MouseExited

    private void BotonPagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPagoMouseExited
        // TODO add your handling code here:
        BotonPago.setBackground(  Color.WHITE);
    }//GEN-LAST:event_BotonPagoMouseExited

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPago;
    private javax.swing.JTextField Camisa;
    private javax.swing.JTextField Cartera;
    private javax.swing.JTextField ISV;
    private javax.swing.JTextField Pantalon;
    private javax.swing.JTextField Perfume;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField TxtF;
    private javax.swing.JTextField Zapato;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JTextField tsub;
    // End of variables declaration//GEN-END:variables
}
