/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Samuel
 */
import java.text.DecimalFormat;
import javax.swing.JOptionPane; 

public class Factura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
        this.setLocationRelativeTo(null);
       InicioZero("0","0","0","0","0");
            
    }
    public void InicioZero(String a, String b, String c, String d, String e){
    
    Perfume.setText(a);
    Cartera.setText(b);
    Pantalon.setText(c);
    Zapato.setText(d);
    Camisa.setText(e);
    }
    public void tomardatoPerfume(int dato)
    {
       
            Perfume.setText(""+dato);
  
    
    
    }
        
    public void Calculo(){
    double Perf,Car,Pan,Zap,Cam,subtotal,impuesto,totalfinal;
   // DecimalFormat df = new DecimalFormat("#.##");
    
    Perf =Integer.parseInt(Perfume.getText());
    Car = Integer.parseInt(Cartera.getText());
    Pan = Integer.parseInt(Pantalon.getText());
    Zap = Integer.parseInt(Zapato.getText());
    Cam = Integer.parseInt(Camisa.getText());
    
    subtotal = Perf+Car+Pan+Zap+Cam;
    String sb = subtotal + "";
     tsub.setText(sb);
    impuesto = subtotal*0.18;
    String isv = String.format("%.2f",impuesto);
     ISV.setText(isv);
    totalfinal= subtotal + impuesto;
    String TFinal = totalfinal + "";
    TxtF.setText(TFinal);
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonPago = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Cartera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ISV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tsub = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtF = new javax.swing.JTextField();
        Perfume = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Pantalon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Zapato = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Camisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FACTURA COMPRA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(6, 6, 458, 55);

        BotonPago.setText("Pagar");
        BotonPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPagoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonPago);
        BotonPago.setBounds(350, 390, 72, 23);

        jButton2.setText("Abortar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 390, 72, 23);

        jButton1.setText("Seguir Comprando");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(135, 390, 130, 23);

        jLabel2.setText("Perfumes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 100, 120, 16);

        Cartera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarteraActionPerformed(evt);
            }
        });
        jPanel1.add(Cartera);
        Cartera.setBounds(150, 130, 64, 22);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ISV 18%");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(297, 310, 70, 16);
        jPanel1.add(ISV);
        ISV.setBounds(360, 300, 71, 22);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Subtotal");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 280, 70, 16);
        jPanel1.add(tsub);
        tsub.setBounds(360, 270, 71, 22);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TotalFinal");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 340, 70, 16);
        jPanel1.add(TxtF);
        TxtF.setBounds(360, 330, 71, 22);

        Perfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfumeActionPerformed(evt);
            }
        });
        jPanel1.add(Perfume);
        Perfume.setBounds(150, 100, 64, 22);

        jLabel6.setText("Carteras");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 130, 60, 16);

        jLabel7.setText("Pantalones");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 170, 60, 16);
        jPanel1.add(Pantalon);
        Pantalon.setBounds(150, 170, 64, 22);

        jLabel8.setText("Zapatos");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 210, 60, 16);
        jPanel1.add(Zapato);
        Zapato.setBounds(150, 210, 64, 22);

        jLabel9.setText("Camisas");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 260, 60, 16);
        jPanel1.add(Camisa);
        Camisa.setBounds(150, 250, 64, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPagoActionPerformed
         Object[] opciones = { "Si", "No"}; 
  
        int decision = JOptionPane.showOptionDialog( 
            null,  
            "¿Desea confirmar su compra?",
            "Opciones", 
            JOptionPane.YES_NO_CANCEL_OPTION, 
            JOptionPane.QUESTION_MESSAGE, // Message type (question icon) 
            null, // Custom icon (null means no custom icon) 
            opciones, 
            opciones[0] 
                
        ); 
                    
        // Check the user's choice and display a 
        // corresponding message 
        if (decision == JOptionPane.YES_OPTION) { 
            // If the user chose 'Yes' 
            // show a message indicating that they are 
            // proceeding 
            JOptionPane.showMessageDialog(null,"Transaccion Confirmada"); 
            
            
            
        } 
        else if (decision == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Transaccion No Confirmada", "Transaccion No Confirmada", JOptionPane.ERROR_MESSAGE);
            
        } 
        

        
    }//GEN-LAST:event_BotonPagoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Operacion Abortada", "Operacion Abortada", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfumeActionPerformed

    private void CarteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarteraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarteraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPago;
    private javax.swing.JTextField Camisa;
    private javax.swing.JTextField Cartera;
    private javax.swing.JTextField ISV;
    private javax.swing.JTextField Pantalon;
    private javax.swing.JTextField Perfume;
    private javax.swing.JTextField TxtF;
    private javax.swing.JTextField Zapato;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tsub;
    // End of variables declaration//GEN-END:variables
}
